// ROOT STORE @/store/index.js
export const CHANGE_COOKIE = 'CHANGE_COOKIE'
export const CHANGE_COOKIE_BOOLEAN = 'CHANGE_COOKIE_BOOLEAN'
export const ERASE_COOKIE = 'ERASE_COOKIE'

// MODULES @/store/modules/StoreModules.js
export const LOAD_MODULES = 'LOAD_MODULES'
export const CHANGE_MODULES_LOADED_STATE = 'CHANGE_MODULES_LOADED_STATE'
export const CHANGE_MODULES_ERRORED_STATE = 'CHANGE_MODULES_ERRORED_STATE'
export const SET_ACTIVE_MODULES = 'SET_ACTIVE_MODULES'
export const SET_INACTIVE_MODULES = 'SET_INACTIVE_MODULES'
export const IS_ACTIVE = 'IS_ACTIVE'
export const IS_INACTIVE = 'IS_INACTIVE'
export const REORDER_MODULES = 'REORDER_MODULES'

// PARTS @/store/modules/StoreParts.js
export const LOAD_PART_DATA = 'LOAD_PART_DATA'
export const LOAD_PART_NUMBERS = 'LOAD_PART_NUMBERS'
export const CHANGE_PART_DATA_LOADED_STATE = 'CHANGE_PART_DATA_LOADED_STATE'
export const CHANGE_PART_DATA_ERRORED_STATE = 'CHANGE_PART_DATA_ERRORED_STATE'
export const CHANGE_PART_NUMBERS_LOADED_STATE = 'CHANGE_PART_NUMBERS_LOADED_STATE'
export const CHANGE_PART_NUMBERS_ERRORED_STATE = 'CHANGE_PART_NUMBERS_ERRORED_STATE'
export const LOAD_QUERIED_PART = 'LOAD_QUERIED_PART'
export const CHANGE_QUERIED_PART_LOADED_STATE = 'CHANGE_QUERIED_PART_LOADED_STATE'
export const CHANGE_QUERIED_PART_ERRORED_STATE = 'CHANGE_QUERIED_PART_ERRORED_STATE'
export const CLEAR_QUERIED_PART = 'CLEAR_QUERIED_PART'

// PARTS @/store/modules/StoreOldParts.js
export const LOAD_PARTS = 'LOAD_PARTS'
export const CHANGE_PARTS_LOADED_STATE = 'CHANGE_PARTS_LOADED_STATE'
export const CHANGE_PARTS_ERRORED_STATE = 'CHANGE_PARTS_ERRORED_STATE'
export const CHANGE_PARTS_PARAMS = 'CHANGE_PARTS_PARAMS'

// ROLES @/store/modules/StoreRoles.js
export const LOAD_ROLES = 'LOAD_PARTS'
export const CHANGE_ROLES_LOADED_STATE = 'CHANGE_ROLES_LOADED_STATE'
export const CHANGE_ROLES_ERRORED_STATE = 'CHANGE_ROLES_ERRORED_STATE'
export const SET_ROLE_MODULES = 'SET_ROLE_MODULES'

// DATES @/store/modules/StoreDates.js
export const LOAD_DATES = 'LOAD_DATES'
export const CHANGE_DATES_LOADED_STATE = 'CHANGE_DATES_LOADED_STATE'
export const CHANGE_DATES_ERRORED_STATE = 'CHANGE_DATES_ERRORED_STATE'

// TABLES @/store/modules/StoreTables.js
export const LOAD_TABLE_DATA = 'LOAD_TABLE_DATA'
export const CHANGE_TABLE_DATA_LOADED_STATE = 'CHANGE_TABLE_DATA_LOADED_STATE'
export const CHANGE_TABLE_DATA_ERRORED_STATE = 'CHANGE_TABLE_DATA_ERRORED_STATE'
export const CHANGE_TABLE_CHOICE = 'CHANGE_TABLE_CHOICE'
export const CHANGE_CHOSEN_TABLE = 'CHANGE_CHOSEN_TABLE'
export const CHANGE_CHOSEN_TABLE_LOADED_STATE = 'CHANGE_CHOSEN_TABLE_LOADED_STATE'
